---
- name: "Download elasticsearch"
  get_url:
    dest: "{{ elasticsearch.repo.deb_destination }}"
    url: "{{ elasticsearch.repo.deb_source }}"
    checksum: "{{ elasticsearch.repo.deb_checksum }}"

- name: Install elasticsearch
  become: yes
  apt: deb="{{ elasticsearch.repo.deb_destination }}"

- name: Set elasticsearch configuration
  template: src=elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
  become: yes

- name: Activate decompound plugin for elastic search
  become: yes
  elasticsearch_plugin: state=present name="http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-analysis-decompound/{{elasticsearch_version}}.0/elasticsearch-analysis-decompound-{{elasticsearch_version}}.0-plugin.zip"

- name: restart elasticsearch
  become: yes
  service: name=elasticsearch enabled=yes state=restarted
