---
vagrant_local:
  vm:
    name: default
    provider: virtualbox
    base_box: ubuntu/trusty64
    hostname: default.dev
    aliases:
      - www.default.dev
    ip: 192.168.123.2
    memory: '512'
    cpus: 1
    app_shared_folder:
      source: ./
      target: /var/www
      sync_type: ~
      owner: vagrant
      group: vagrant
      permissions: u=rwX:g=rwX:o=rD
      bindfs: true
    provider_specific:
      parallels:
        base_box: parallels/ubuntu-14.04
      lxc:
        base_box: oxid_esales/trusty64-lxc
        ip: ~
        app_shared_folder:
          sync_type: ~
docker: false
server:
  timezone: Europe/Berlin
  locale: en_US.UTF-8
  apt_mirror: http://us.archive.ubuntu.com/ubuntu/
  unattended_upgrade: false
  packages: ~
  personal_packages: ~
  forceless_umount_url: https://github.com/OXID-eSales/oxvm_assets/blob/master/umount?raw=true
apache:
  install: true
  docroot: /vagrant
  servername: myApp.vb
  user: "{{ vagrant_local.vm.app_shared_folder.owner }}"
  group: "{{ vagrant_local.vm.app_shared_folder.group }}"
mysql:
  install: true
  root_password: '123'
  database: db
  user: user
  password: password
  dump: ''
zendguard_version_name: 'zend-loader-php5.6-linux-x86_64'
php:
  install: true
  packages:
    - php5.6-cli
    - php5.6-intl
    - php5.6-mcrypt
    - php5.6-mysql
    - php5.6-gd
    - php5.6-curl
    - php5.6-xml
    - php5.6-zip
  version: ~
  display_errors: On
  extension_dir: '/usr/lib/php/20131226/'
  phpbrew:
    cache:
      repo: 'https://github.com/OXID-eSales/oxvm_assets'
      ref: 'phpbrew_builds'
      depth: 1
      update: true
  xdebug:
    install: '1'
    host: ~
  composer:
    timeout: false
    installer_url: https://getcomposer.org/installer
    install: '1'
    github_token: ~
    prestissimo:
      install: false
  pecl_packages: ~
  zendguard:
    install: false
    pkg_url: "https://github.com/OXID-eSales/oxvm_assets/blob/master/{{ zendguard_version_name }}.tar.gz?raw=true"
  ioncube:
    install: false
    pkg_url: http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64_6.0.6.tar.gz
mailhog:
  install: false
  web_port: 8025
  smtp_port: 1025
  pkg_url: 'https://github.com/mailhog/MailHog/releases/download/v0.1.8/MailHog_linux_amd64'
  sendmail_url: 'https://github.com/mailhog/mhsendmail/releases/download/v0.1.9/mhsendmail_linux_amd64'
  web_alias: '/mail/'
adminer:
  install: false
  pkg_url: 'https://raw.githubusercontent.com/OXID-eSales/oxvm_assets/master/adminer-4.2.5-mysql-en.php'
  web_alias: '/adminer/'
adminer_editor:
  install: false
  pkg_url: 'https://raw.githubusercontent.com/OXID-eSales/oxvm_assets/master/editor-4.2.5-mysql-en.php'
  web_alias: '/adminer_editor/'
varnish:
  install: false
  repo:
    source: 'deb https://repo.varnish-cache.org/ubuntu/ trusty varnish-4.0'
    key: 'https://repo.varnish-cache.org/GPG-key.txt'
    https: '1'
  daemon_path: /usr/sbin/varnishd
  package_name: varnish
  default_config:
    source: ~
    target: /etc/varnish/default.vcl
java:
  install: false
  packages: [openjdk-7-jre]
elasticsearch_version: 2.3.3
elasticsearch:
  install: false
  repo:
    deb_destination: "/tmp/elasticsearch-{{elasticsearch_version}}.deb"
    deb_source: "https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/{{elasticsearch_version}}/elasticsearch-{{elasticsearch_version}}.deb"
    deb_checksum: 'sha1:8385dda7aa3870a3b13fc1df91d8b750d940700e'
