---
vagrant_local:
  vm:
    name: default
    provider: virtualbox
    base_box: bento/ubuntu-18.04
    hostname: default.local
    aliases:
      - www.default.local
    ip: 192.168.123.2
    memory: '1024'
    cpus: 1
    ioapic: "on"
    hwvirtex: "on"
    nestedpaging: "on"
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    app_shared_folder:
      source: www
      target: /var/www
      sync_type: ~
      owner: vagrant
      group: vagrant
      permissions: u=rwX:g=rwX:o=rD
      bindfs: true
    provider_specific:
      lxc:
        base_box: oxid_esales/bionic64-lxc
        ip: ~
        app_shared_folder:
          sync_type: ~
docker: false
server:
  timezone: Europe/Berlin
  locale: en_US.UTF-8
  apt_mirror: http://de.archive.ubuntu.com/ubuntu/
  packages:
    - git
    - bash-completion
    - zip
  personal_packages: ~
  forceless_umount_url: https://github.com/OXID-eSales/oxvm_assets/blob/master/umount?raw=true
landing:
  install: true
apache:
  install: true
  docroot: /var/www
  servername: "{{ vagrant_local.vm.hostname }}"
  user: "{{ vagrant_local.vm.app_shared_folder.owner }}"
  group: "{{ vagrant_local.vm.app_shared_folder.group }}"
mysql:
  install: true
  version: '5.7'
  root_password: '123'
  database: db
  user: user
  password: password
  dump: ''
  in_memory: false
  sql_mode: 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
  grants: "`db`.*:ALL"
mariadb:
  install: false
  version: '10.4'
  root_password: '123'
  database: db
  user: user
  password: password
  grants: "`db`.*:ALL"
php:
  install: true
  packages:
    - cli
    - intl
    - mysql
    - gd
    - curl
    - xml
    - sqlite3
    - zip
    - mbstring
  version: 7.1
  display_errors: On
  xdebug:
    install: '1'
    host: ~
  composer:
    timeout: 900
    installer_url: https://getcomposer.org/installer
    install: '1'
    major_version: 2
    github_token: ~
    gitlab_token: ~
    gitlab_url: ~
    http_basic: ~
    prestissimo:
      install: false
  pecl_packages: ~
  zendguard:
    install: false
    pkg_url: https://github.com/OXID-eSales/oxvm_assets/blob/master/zend-loader-php5.6-linux-x86_64.tar.gz?raw=true
  ioncube:
    install: false
    pkg_url: http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64_6.0.6.tar.gz
mailhog:
  install: false
  web_port: 8025
  smtp_port: 1025
  pkg_url: 'https://github.com/mailhog/MailHog/releases/download/v0.1.8/MailHog_linux_amd64'
  sendmail_url: 'https://github.com/mailhog/mhsendmail/releases/download/v0.1.9/mhsendmail_linux_amd64'
  web_alias: '/mail/'
adminer:
  install: false
  pkg_url: 'https://raw.githubusercontent.com/OXID-eSales/oxvm_assets/master/adminer-4.3.1-mysql-en.php'
  web_alias: '/adminer/'
adminer_editor:
  install: false
  pkg_url: 'https://raw.githubusercontent.com/OXID-eSales/oxvm_assets/master/editor-4.3.1-mysql-en.php'
  web_alias: '/adminer_editor/'
varnish:
  install: false
  repo:
    source: 'deb https://packagecloud.io/varnishcache/varnish40/ubuntu/ trusty main'
    key: 'https://packagecloud.io/varnishcache/varnish40/gpgkey'
    https: '1'
  daemon_path: /usr/sbin/varnishd
  package_name: varnish=4.0.*
  default_config:
    source: ~
    target: /etc/varnish/default.vcl
java:
  install: false
  packages:
    - libpulse0
    - libsctp1
    - openjdk-11-jre-headless
  repo_libjpg:
    deb_destination: '/tmp/libjpeg62-turbo_1.5.2-2+b1_amd64.deb'
    deb_source: 'https://github.com/OXID-eSales/oxvm_assets/raw/master/libjpeg62-turbo_1.5.2-2+b1_amd64.deb'
    deb_checksum: 'sha256:19fa4d492c59e051f00334b1a13bcd3579b3c199623a23e68476cb46d5b1d590'
  repo_java7:
    deb_destination: '/tmp/openjdk-7-jre-headless_7u161-2.6.12-1_amd64.deb'
    deb_source: 'https://github.com/OXID-eSales/oxvm_assets/raw/master/openjdk-7-jre-headless_7u161-2.6.12-1_amd64.deb'
    deb_checksum: 'sha256:79f4582ffaedafd0f45195df9be5ff50ce8ccedf9163ed212d1e1ad031247695'
  alternative: '/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java'
elasticsearch:
  install: false
  repo:
    deb_destination: '/tmp/elasticsearch_2_3_3.deb'
    deb_source: 'https://github.com/OXID-eSales/oxvm_assets/raw/master/elasticsearch-2.3.3.deb'
    deb_checksum: 'sha1:8385dda7aa3870a3b13fc1df91d8b750d940700e'
selenium:
  install: false
  package:
    firefox:
      tar_url: https://github.com/OXID-eSales/oxvm_assets/raw/master/firefox-31.6.0esr.tar.bz2
      tar_checksum: sha256:c1d8b1689ddc6cb99be549809c845edafa9c8eb15b8795880419f005f2c3fdf6
    self:
      jar_url: https://github.com/OXID-eSales/oxvm_assets/raw/master/selenium-server-standalone-2.47.1.jar
      jar_checksum: sha256:45665f3bb4dffb668981258faff91823db4a1f6250fd24fd6698ec159a4aeb8a
doxygen:
  install: false
